### ISSUE TITLE
mlcp task fails when using java 11 on windows

### ISSUE THREAD

**Issue by derms** [marklogic/marklogic-contentpump#169]
When using mlcp 10.0.4 in a gradle task on windows with java 11, it fails with the following error -

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.apache.hadoop.util.GenericOptionsParser.preProcessForWindows(GenericOptionsParser.java:438)
        at org.apache.hadoop.util.GenericOptionsParser.parseGeneralOptions(GenericOptionsParser.java:484)
        at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:170)
        at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:153)
        at com.marklogic.contentpump.ContentPump.runCommand(ContentPump.java:120)
        at com.marklogic.contentpump.ContentPump.main(ContentPump.java:74)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at org.apache.hadoop.util.Shell.<clinit>(Shell.java:49)
        ... 6 more
```

This error is described here

https://issues.apache.org/jira/browse/HADOOP-14586

The solution is to upgrade the hadoop library to 2.7.4 or greater (currently mlcp uses version 2.6.0)

**Comment by hansenmc** [comment]
We might consider using https://dependabot.com/ to help keep dependencies up to date.

**Comment by hansenmc** [comment]
https://stackoverflow.com/q/68861154/14419

**Comment by grtjn** [comment]
As a workaround, you can force hadoop lib to a higher 2.x version using something like this: https://gist.github.com/grtjn/6258e573ec61e92e802354ad4f091074#file-build-gradle-L22

**Comment by yunzvanessa** [comment]
Thanks Geert! Upgrading Hadoop lib to a higher version will cause compatibility issues with the current MLCP repo. It's a bigger project and will be addressed in a later release.

Thanks,
Vanessa

**Comment by grtjn** [comment]
Beware that if you do force hadoop to a particular version (like I suggested above), that this might cause issues when upgrading MLCP later on.  It is time to drop the force line for hadoop when you start getting messages like:

```
java.lang.NoClassDefFoundError: org/apache/hadoop/crypto/key/KeyProviderTokenIssuer
```

Sharing this for posterity, in case someone followed my advice..

**Comment by grtjn** [comment]
PS: I think this ticket is solved. MLCP 11.0.2 seems to use hadoop 3.3.4, and runs just fine from the looks of it.

**Comment by rjrudin** [comment]
Closing as MLCP now requires Java 11.
