### ISSUE TITLE
ArrayIndexOutOfBoundsException when importing to a database with no forest attached.

### ISSUE THREAD

**Issue by jxchen-us** [marklogic/marklogic-contentpump#20]
[jchen@jchen-z620 mlcp]$ mlcp-9.0/bin/mlcp.sh import -username admin -password admin -host jchen -copy_collections -port 5275 -input_file_type archive -input_file_path /tmp/dump
16/09/01 17:28:19 INFO contentpump.LocalJobRunner: Content type: XML
16/09/01 17:28:19 INFO contentpump.ContentPump: Job name: local_925113862_1
16/09/01 17:28:19 INFO contentpump.FileAndDirectoryInputFormat: Total input paths to process : 1
16/09/01 17:28:21 ERROR contentpump.MultithreadedMapper: 0
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.marklogic.contentpump.DatabaseContentWriter.write(DatabaseContentWriter.java:140)
	at com.marklogic.mapreduce.ContentWriter.write(ContentWriter.java:1)
	at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
	at com.marklogic.contentpump.ImportDocumentMapper.map(ImportDocumentMapper.java:54)
	at com.marklogic.contentpump.ImportDocumentMapper.map(ImportDocumentMapper.java:1)
	at com.marklogic.contentpump.BaseMapper.runThreadSafe(BaseMapper.java:51)
	at com.marklogic.contentpump.MultithreadedMapper$MapRunner.run(MultithreadedMapper.java:379)
	at com.marklogic.contentpump.MultithreadedMapper.run(MultithreadedMapper.java:215)
	at com.marklogic.contentpump.LocalJobRunner$LocalMapTask.call(LocalJobRunner.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
16/09/01 17:28:21 INFO contentpump.LocalJobRunner:  completed 0%
16/09/01 17:28:21 INFO contentpump.LocalJobRunner: com.marklogic.mapreduce.MarkLogicCounter: 
16/09/01 17:28:21 INFO contentpump.LocalJobRunner: INPUT_RECORDS: 4
16/09/01 17:28:21 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS: 4
16/09/01 17:28:21 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_COMMITTED: 0
16/09/01 17:28:21 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_FAILED: 0
16/09/01 17:28:21 INFO contentpump.LocalJobRunner: Total execution time: 1 sec

**Comment by sravanr** [comment]
Verified with latest nightly mlcp build and added regression test mlcp-set-copy-col-perm-qlty-false.xml

I see the following now.

16/09/27 10:30:05 INFO contentpump.FileAndDirectoryInputFormat: Total input paths to process : 8
16/09/27 10:30:05 ERROR contentpump.LocalJobRunner: Error checking output specification: 
16/09/27 10:30:05 ERROR contentpump.LocalJobRunner: java.io.IOException: Target database has no forests attached: check forests in database

st
