### ISSUE TITLE
REGR:test for bug 20059 i.e. bug20059.xml is failing in regression form 17 sept 2016

### ISSUE THREAD

**Issue by sravanr** [marklogic/marklogic-contentpump#31]
I see test bug20059.xml is failing in regression from 17th sept, because following reason

/space/b8_0/qa/mlcp/runmlcp.sh /space/b8_0/qa import -username admin -password admin -host localhost -port 5275 -copy_collections true -copy_permissions true -copy_properties true -copy_quality true -input_file_path file:////space/b8_0/qa/mlcp/data/export/bug18908/1 -input_file_type archive 

stderr/out from shell cmd: 16/09/20 14:32:56 INFO contentpump.LocalJobRunner: Content type: XML
16/09/20 14:32:57 INFO contentpump.FileAndDirectoryInputFormat: Total input paths to process : 4
16/09/20 14:32:57 ERROR contentpump.LocalJobRunner: Error running task: 
com.thoughtworks.xstream.mapper.CannotResolveClassException: com.marklogic.ps.xqsync.XQSyncDocumentMetadata
	at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:56)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:45)
	at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:133)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1052)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1036)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:912)
	at com.marklogic.contentpump.DocumentMetadata.fromXML(DocumentMetadata.java:70)
	at com.marklogic.contentpump.ArchiveRecordReader.getMetadataFromStream(ArchiveRecordReader.java:185)
	at com.marklogic.contentpump.ArchiveRecordReader.nextKeyValue(ArchiveRecordReader.java:128)
	at com.marklogic.contentpump.LocalJobRunner$TrackingRecordReader.nextKeyValue(LocalJobRunner.java:444)
	at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:144)
	at com.marklogic.contentpump.LocalJobRunner$LocalMapTask.call(LocalJobRunner.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
16/09/20 14:32:58 INFO contentpump.LocalJobRunner:  completed 25%
16/09/20 14:33:10 INFO contentpump.LocalJobRunner:  completed 50%
16/09/20 14:33:10 INFO contentpump.LocalJobRunner:  completed 75%
16/09/20 14:33:10 INFO contentpump.LocalJobRunner: com.marklogic.mapreduce.MarkLogicCounter: 
16/09/20 14:33:10 INFO contentpump.LocalJobRunner: INPUT_RECORDS: 11231
16/09/20 14:33:10 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS: 11231
16/09/20 14:33:10 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_COMMITTED: 11231
16/09/20 14:33:10 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_FAILED: 0
16/09/20 14:33:10 INFO contentpump.LocalJobRunner: Total execution time: 13 sec

**Comment by jxchen-us** [comment]
I reproduced on b8 using a b8 qa checkout.  I could not reproduce on trunk with a trunk qa checkout.

**Comment by jxchen-us** [comment]
I copied my local build of mlcp-8.0-bin.zip to $QA_HOME/mlcp dir, and the test passed:

[jchen@jchen-z620 mlcp]$ cp deliverable/mlcp-8.0-bin.zip /space/projects/qa-b8/mlcp/mlcp.zip
[jchen@jchen-z620 mlcp]$ cp deliverable/mlcp-8.0-bin.zip /space/projects/qa-b8/mlcp/marklogic-contentpump.zip

Not sure how the two are different.

**Comment by jxchen-us** [comment]
See checkin for #30:

 https://github.com/marklogic/marklogic-contentpump/commit/14adf3cb6427d37142d51a6174ca83e1dd677ec9
https://github.com/marklogic/marklogic-contentpump/commit/ec94711d9a6dc924342bbbd16cc29d56ba01b565

**Comment by sravanr** [comment]
bug20059.xml is passing with latest nightly build.
