### ISSUE TITLE
Unable to import xml containing a unicode characters as aggregates

### ISSUE THREAD

**Issue by mattsunsjf** [marklogic/marklogic-contentpump#47]
Input file:

``` xml
<p><q>b Justus-Liebig-Universität , Gie&#x1d4b7;en , Germany.</q></p>
```

Mlcp command and logging:

``` bash
[jsun@msun-z620 mlcp-8.0]$ bin/mlcp.sh import -username admin -password admin -host msun -port 8000 -mode local -input_file_path /space/tmp/special-char.xml -input_file_type aggregates -aggregate_record_element q -generate_uri
16/10/25 10:15:41 INFO contentpump.LocalJobRunner: Content type: XML
16/10/25 10:15:42 INFO contentpump.FileAndDirectoryInputFormat: Total input paths to process : 1
16/10/25 10:15:44 ERROR mapreduce.ContentWriter: XDMP-DOCCHARREF: Invalid character reference "55349" at /space/tmp/special-char.xml-0-1 line 1
16/10/25 10:15:44 WARN mapreduce.ContentWriter: Failed document /space/tmp/special-char.xml-0-1 in file:/space/tmp/special-char.xml at line 1:7
16/10/25 10:15:44 INFO contentpump.LocalJobRunner:  completed 100%
16/10/25 10:15:44 INFO contentpump.LocalJobRunner: com.marklogic.mapreduce.MarkLogicCounter:
16/10/25 10:15:44 INFO contentpump.LocalJobRunner: INPUT_RECORDS: 1
16/10/25 10:15:44 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS: 1
16/10/25 10:15:44 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_COMMITTED: 1
16/10/25 10:15:44 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_FAILED: 0
16/10/25 10:15:44 INFO contentpump.LocalJobRunner: Total execution time: 2 sec
```

However, if this document is ingested as plain xml, it went through:

``` bash
[jsun@msun-z620 mlcp-8.0]$ bin/mlcp.sh import -username admin -password admin -host msun -port 8000 -mode local -input_file_path /space/tmp/special-char.xml
16/10/25 10:11:20 INFO contentpump.LocalJobRunner: Content type is set to MIXED.  The format of the  inserted documents will be determined by the MIME  type specification configured on MarkLogic Server.
16/10/25 10:11:21 INFO contentpump.FileAndDirectoryInputFormat: Total input paths to process : 1
16/10/25 10:11:21 INFO contentpump.LocalJobRunner:  completed 100%
16/10/25 10:11:21 INFO contentpump.LocalJobRunner: com.marklogic.mapreduce.MarkLogicCounter:
16/10/25 10:11:21 INFO contentpump.LocalJobRunner: INPUT_RECORDS: 1
16/10/25 10:11:21 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS: 1
16/10/25 10:11:21 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_COMMITTED: 1
16/10/25 10:11:21 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_FAILED: 0
16/10/25 10:11:21 INFO contentpump.LocalJobRunner: Total execution time: 0 sec
```

**Comment by mattsunsjf** [comment]
It's actually the character `&#x1d4b7;` caused the error, not those German characters. `&#x1d4b7;` is the escaped form of [MATHEMATICAL SCRIPT SMALL B](http://www.fileformat.info/info/unicode/char/1d4b7/index.htm)

**Comment by sravanr** [comment]
Used the below command:

mlcp/mlcp-9.0/bin/mlcp.sh  import -username admin -password admin -host engrlab-131-083.engrlab.marklogic.com  -port 8000 -mode local -input_file_path /tmp/special-char.xml -input_file_type aggregates -aggregate_record_element q -generate_uri
special-char.xml:
<p><q>b Justus-Liebig-Universität , Gie&#x1d4b7;en , Germany.</q></p>

I am getting the below sample exceptions,
ERROR contentpump.MultithreadedMapper: Parsing error
ERROR contentpump.MultithreadedMapper: java.lang.NullPointerException  

Please find the attached file: 42812_MLCP_console_errorlog.txt for more info on this.

 42812_MLCP_console_errorlog.txt

**Comment by sravanr** [comment]
```
[ypaladug@engrlab-131-083 qa]$ mlcp/mlcp-9.0/bin/mlcp.sh  import -username admin -password admin -host engrlab-131-083.engrlab.marklogic.com  -port 8000 -mode local -input_file_path /tmp/special-char.xml -input_file_type aggregates -aggregate_record_element q -generate_uri
16/12/07 19:02:31 DEBUG contentpump.ContentPump: Command: IMPORT
16/12/07 19:02:31 DEBUG contentpump.ContentPump: Arguments: -username admin -password admin -host engrlab-131-083.engrlab.marklogic.com -port 8000 -mode local -input_file_path /tmp/special-char.xml -input_file_type aggregates -aggregate_record_element q -generate_uri
16/12/07 19:02:31 DEBUG contentpump.ContentPump: Running in: localmode
16/12/07 19:02:31 INFO contentpump.LocalJobRunner: Content type: XML
16/12/07 19:02:32 INFO contentpump.ContentPump: Job name: local_864518043_1
16/12/07 19:02:32 DEBUG contentpump.LocalJobRunner: Thread pool size: 4
16/12/07 19:02:32 INFO contentpump.FileAndDirectoryInputFormat: Total input paths to process : 1
16/12/07 19:02:32 DEBUG contentpump.LocalJobRunner: Thread Count for Split#0 : 4
16/12/07 19:02:32 DEBUG contentpump.MultithreadedMapper: Running with 4 threads
16/12/07 19:02:32 ERROR contentpump.AggregateXMLReader: Parsing error
javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,32]
Message: Invalid byte 2 of 3-byte UTF-8 sequence.
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:591)
        at com.marklogic.contentpump.AggregateXMLReader.nextKeyValue(AggregateXMLReader.java:468)
        at com.marklogic.contentpump.LocalJobRunner$TrackingRecordReader.nextKeyValue(LocalJobRunner.java:444)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at com.marklogic.contentpump.MultithreadedMapper$SubMapRecordReader.nextKeyValue(MultithreadedMapper.java:275)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at com.marklogic.contentpump.BaseMapper.runThreadSafe(BaseMapper.java:45)
        at com.marklogic.contentpump.MultithreadedMapper$MapRunner.run(MultithreadedMapper.java:379)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
16/12/07 19:02:32 ERROR contentpump.MultithreadedMapper: Parsing error
java.io.IOException: Parsing error
        at com.marklogic.contentpump.AggregateXMLReader.nextKeyValue(AggregateXMLReader.java:554)
        at com.marklogic.contentpump.LocalJobRunner$TrackingRecordReader.nextKeyValue(LocalJobRunner.java:444)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at com.marklogic.contentpump.MultithreadedMapper$SubMapRecordReader.nextKeyValue(MultithreadedMapper.java:275)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at com.marklogic.contentpump.BaseMapper.runThreadSafe(BaseMapper.java:45)
        at com.marklogic.contentpump.MultithreadedMapper$MapRunner.run(MultithreadedMapper.java:379)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,32]
Message: Invalid byte 2 of 3-byte UTF-8 sequence.
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:591)
        at com.marklogic.contentpump.AggregateXMLReader.nextKeyValue(AggregateXMLReader.java:468)
        ... 13 more
16/12/07 19:02:32 ERROR contentpump.AggregateXMLReader: Parsing error
javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,32]
Message: XML document structures must start and end within the same entity.
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596)
        at com.marklogic.contentpump.AggregateXMLReader.nextKeyValue(AggregateXMLReader.java:468)
        at com.marklogic.contentpump.LocalJobRunner$TrackingRecordReader.nextKeyValue(LocalJobRunner.java:444)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at com.marklogic.contentpump.MultithreadedMapper$SubMapRecordReader.nextKeyValue(MultithreadedMapper.java:275)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at com.marklogic.contentpump.BaseMapper.runThreadSafe(BaseMapper.java:45)
        at com.marklogic.contentpump.MultithreadedMapper$MapRunner.run(MultithreadedMapper.java:379)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
16/12/07 19:02:32 ERROR contentpump.MultithreadedMapper: Parsing error
java.io.IOException: Parsing error
        at com.marklogic.contentpump.AggregateXMLReader.nextKeyValue(AggregateXMLReader.java:554)
        at com.marklogic.contentpump.LocalJobRunner$TrackingRecordReader.nextKeyValue(LocalJobRunner.java:444)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at com.marklogic.contentpump.MultithreadedMapper$SubMapRecordReader.nextKeyValue(MultithreadedMapper.java:275)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at com.marklogic.contentpump.BaseMapper.runThreadSafe(BaseMapper.java:45)
        at com.marklogic.contentpump.MultithreadedMapper$MapRunner.run(MultithreadedMapper.java:379)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,32]
Message: XML document structures must start and end within the same entity.
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596)
        at com.marklogic.contentpump.AggregateXMLReader.nextKeyValue(AggregateXMLReader.java:468)
        ... 13 more
16/12/07 19:02:32 ERROR contentpump.MultithreadedMapper:
java.lang.NullPointerException
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1788)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanContent(XMLEntityScanner.java:954)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2820)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:553)
        at com.marklogic.contentpump.AggregateXMLReader.nextKeyValue(AggregateXMLReader.java:468)
        at com.marklogic.contentpump.LocalJobRunner$TrackingRecordReader.nextKeyValue(LocalJobRunner.java:444)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at com.marklogic.contentpump.MultithreadedMapper$SubMapRecordReader.nextKeyValue(MultithreadedMapper.java:275)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at com.marklogic.contentpump.BaseMapper.runThreadSafe(BaseMapper.java:45)
        at com.marklogic.contentpump.MultithreadedMapper$MapRunner.run(MultithreadedMapper.java:379)
        at com.marklogic.contentpump.MultithreadedMapper.run(MultithreadedMapper.java:215)
        at com.marklogic.contentpump.LocalJobRunner$LocalMapTask.call(LocalJobRunner.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
16/12/07 19:02:32 ERROR contentpump.MultithreadedMapper:
java.lang.NullPointerException
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1788)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanContent(XMLEntityScanner.java:954)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2820)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:553)
        at com.marklogic.contentpump.AggregateXMLReader.nextKeyValue(AggregateXMLReader.java:468)
        at com.marklogic.contentpump.LocalJobRunner$TrackingRecordReader.nextKeyValue(LocalJobRunner.java:444)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at com.marklogic.contentpump.MultithreadedMapper$SubMapRecordReader.nextKeyValue(MultithreadedMapper.java:275)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at com.marklogic.contentpump.BaseMapper.runThreadSafe(BaseMapper.java:45)
        at com.marklogic.contentpump.MultithreadedMapper$MapRunner.run(MultithreadedMapper.java:379)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
16/12/07 19:02:32 INFO contentpump.LocalJobRunner:  completed 0%
16/12/07 19:02:32 INFO contentpump.LocalJobRunner: com.marklogic.mapreduce.MarkLogicCounter:
16/12/07 19:02:32 INFO contentpump.LocalJobRunner: INPUT_RECORDS: 0
16/12/07 19:02:32 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS: 0
16/12/07 19:02:32 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_COMMITTED: 0
16/12/07 19:02:32 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_FAILED: 0
16/12/07 19:02:32 INFO contentpump.LocalJobRunner: Total execution time: 0 sec
```

**Comment by mattsunsjf** [comment]
I will fix the NPE problem. But let me make sure, are you giving an invalid xml to mlcp as input?

**Comment by mattsunsjf** [comment]
I don't reproduce. 

``` bash
[jsun@msun-z620 mlcp-9.0]$ bin/mlcp.sh import -username admin -password admin -host msun  -port 8000 -mode local -input_file_path /space/tmp/special-char.xml -input_file_type aggregates -aggregate_record_element q -generate_uri
16/12/08 10:57:29 DEBUG contentpump.ContentPump: Command: IMPORT
16/12/08 10:57:29 DEBUG contentpump.ContentPump: Arguments: -username admin -password admin -host msun -port 8000 -mode local -input_file_path /space/tmp/special-char.xml -input_file_type aggregates -aggregate_record_element q -generate_uri
16/12/08 10:57:29 DEBUG contentpump.ContentPump: Running in: localmode
16/12/08 10:57:29 INFO contentpump.LocalJobRunner: Content type: XML
16/12/08 10:57:30 INFO contentpump.ContentPump: Job name: local_1721263359_1
16/12/08 10:57:30 DEBUG contentpump.LocalJobRunner: Thread pool size: 4
16/12/08 10:57:30 INFO contentpump.FileAndDirectoryInputFormat: Total input paths to process : 1
16/12/08 10:57:30 DEBUG contentpump.LocalJobRunner: Thread Count for Split#0 : 4
16/12/08 10:57:30 DEBUG contentpump.MultithreadedMapper: Running with 4 threads
16/12/08 10:57:30 DEBUG mapreduce.ContentWriter: Connect to msun
16/12/08 10:57:30 INFO contentpump.LocalJobRunner:  completed 100%
16/12/08 10:57:30 INFO contentpump.LocalJobRunner: com.marklogic.mapreduce.MarkLogicCounter:
16/12/08 10:57:30 INFO contentpump.LocalJobRunner: INPUT_RECORDS: 1
16/12/08 10:57:30 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS: 1
16/12/08 10:57:30 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_COMMITTED: 1
16/12/08 10:57:30 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_FAILED: 0
16/12/08 10:57:30 INFO contentpump.LocalJobRunner: Total execution time: 0 sec
```

**Comment by sravanr** [comment]
I am not able to attach the file, I found Yeshwanth used a file which is not UTF8 encoded, so that is the reason for the above stack.

If I try the above special charecters in utf8, working fine, but I see NullPointerExceptions when we used not UTF8 file so I am expecting them to be fixed as part of this bug.

you can find the file we used to get the above stack at /project/qa/skottam/special-char.xml

**Comment by mattsunsjf** [comment]
The original reported bug has been fixed already. The NPE is a separate one and a corner case, I will create another bug on 9.0.1 tracking it. Please test the original bug for EA4.

**Comment by sravanr** [comment]
We have validated the document with UTF8 encoding and its working.
