### ISSUE TITLE
MLCP COPY command with ssl throws IO Exception

### ISSUE THREAD

**Issue by sravanr** [marklogic/marklogic-contentpump#48]
Here is the command I am using 

```
/space/Head/qa/mlcp/runmlcpHadoop.sh /space/Head/qa copy -input_username admin -input_password admin -input_host engrlab-130-159.engrlab.marklogic.com -input_port 5275 -copy_collections true -copy_permissions true -copy_properties true -copy_quality true -output_username admin -output_password admin -output_host engrlab-130-159.engrlab.marklogic.com -output_port 9112  
```

runmlcpHadoop.sh will handle the SSL setting and modify the  options to have -conf  like below
```
stderr/out from shell cmd: Today is SSL and Client_CERT enabled: true

COPY -conf /space/Head/qa/mlcp/mlcp-9.0/conf/MlcpSSLConfig.xml -input_username admin -input_password admin -input_host engrlab-130-159.engrlab.marklogic.com -input_port 5275 -copy_collections true -copy_permissions true -copy_properties true -copy_quality true -output_username admin -output_password admin -output_host engrlab-130-159.engrlab.marklogic.com -output_port 9112
```

and 
cat /space/Head/qa/mlcp/mlcp-9.0/conf/MlcpSSLConfig.xml
```
<configuration>
	<property>
		<name>mapreduce.marklogic.input.usessl</name>
		<value>true</value>
	</property>
	<property>
		<name>mapreduce.marklogic.input.ssloptionsclass</name>
		<value>test.hadoop.SslOptions</value>
	</property>
	<property>
		<name>mapreduce.marklogic.output.usessl</name>
		<value>true</value>
	</property>
	<property>
		<name>mapreduce.marklogic.output.ssloptionsclass</name>
		<value>test.hadoop.SslOptions</value>
	</property>
</configuration>

```
I see the following on the console

```
16/11/08 10:31:14 INFO client.RMProxy: Connecting to ResourceManager at rh7v-intel64-cdh-1.marklogic.com/172.18.133.113:8032
16/11/08 10:31:45 ERROR contentpump.ContentPump: Error running a ContentPump job
java.io.IOException: java.io.IOException: com.marklogic.xcc.exceptions.ServerConnectionException: SSL wrapped byte channel
 [Session: user=admin, cb={default} [ContentSource: user=admin, cb={none} [provider: SSLconn address=engrlab-130-159.engrlab.marklogic.com/172.18.130.159:9112, pool=0/64]]]
 [Client: XCC/9.0-1]
	at com.marklogic.mapreduce.MarkLogicOutputFormat.checkOutputSpecs(MarkLogicOutputFormat.java:95)
	at org.apache.hadoop.mapreduce.JobSubmitter.checkSpecs(JobSubmitter.java:562)
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:432)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1296)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1293)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1293)
	at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1314)
	at com.marklogic.contentpump.ContentPump.submitJob(ContentPump.java:304)
	at com.marklogic.contentpump.ContentPump.runCommand(ContentPump.java:205)
	at com.marklogic.contentpump.ContentPump.main(ContentPump.java:63)
Caused by: java.io.IOException: com.marklogic.xcc.exceptions.ServerConnectionException: SSL wrapped byte channel
 [Session: user=admin, cb={default} [ContentSource: user=admin, cb={none} [provider: SSLconn address=engrlab-130-159.engrlab.marklogic.com/172.18.130.159:9112, pool=0/64]]]
 [Client: XCC/9.0-1]
	at com.marklogic.mapreduce.ContentOutputFormat.checkOutputSpecs(ContentOutputFormat.java:233)
	at com.marklogic.mapreduce.MarkLogicOutputFormat.checkOutputSpecs(MarkLogicOutputFormat.java:92)
	... 12 more
Caused by: com.marklogic.xcc.exceptions.ServerConnectionException: SSL wrapped byte channel
 [Session: user=admin, cb={default} [ContentSource: user=admin, cb={none} [provider: SSLconn address=engrlab-130-159.engrlab.marklogic.com/172.18.130.159:9112, pool=0/64]]]
 [Client: XCC/9.0-1]
	at com.marklogic.xcc.impl.handlers.AbstractRequestController.runRequest(AbstractRequestController.java:149)
	at com.marklogic.xcc.impl.SessionImpl.submitRequestInternal(SessionImpl.java:437)
	at com.marklogic.xcc.impl.SessionImpl.submitRequest(SessionImpl.java:432)
	at com.marklogic.mapreduce.ContentOutputFormat.initialize(ContentOutputFormat.java:374)
	at com.marklogic.mapreduce.ContentOutputFormat.checkOutputSpecs(ContentOutputFormat.java:165)
	... 13 more
Caused by: java.io.EOFException: SSL wrapped byte channel
	at com.marklogic.io.SslByteChannel.handleHandshake(SslByteChannel.java:442)
	at com.marklogic.io.SslByteChannel.pushToEngine(SslByteChannel.java:401)
	at com.marklogic.io.SslByteChannel.write(SslByteChannel.java:361)
	at com.marklogic.http.HttpChannel.writeBuffer(HttpChannel.java:388)
	at com.marklogic.http.HttpChannel.writeHeaders(HttpChannel.java:380)
	at com.marklogic.http.HttpChannel.flushRequest(HttpChannel.java:361)
	at com.marklogic.http.HttpChannel.receiveMode(HttpChannel.java:286)
	at com.marklogic.http.HttpChannel.getResponseCode(HttpChannel.java:193)
	at com.marklogic.xcc.impl.handlers.EvalRequestController.serverDialog(EvalRequestController.java:76)
	at com.marklogic.xcc.impl.handlers.AbstractRequestController.runRequest(AbstractRequestController.java:88)
	... 17 more
java.io.IOException: java.io.IOException: com.marklogic.xcc.exceptions.ServerConnectionException: SSL wrapped byte channel
 [Session: user=admin, cb={default} [ContentSource: user=admin, cb={none} [provider: SSLconn address=engrlab-130-159.engrlab.marklogic.com/172.18.130.159:9112, pool=0/64]]]
 [Client: XCC/9.0-1]
	at com.marklogic.mapreduce.MarkLogicOutputFormat.checkOutputSpecs(MarkLogicOutputFormat.java:95)
	at org.apache.hadoop.mapreduce.JobSubmitter.checkSpecs(JobSubmitter.java:562)
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:432)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1296)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1293)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1293)
	at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1314)
	at com.marklogic.contentpump.ContentPump.submitJob(ContentPump.java:304)
	at com.marklogic.contentpump.ContentPump.runCommand(ContentPump.java:205)
	at com.marklogic.contentpump.ContentPump.main(ContentPump.java:63)
Caused by: java.io.IOException: com.marklogic.xcc.exceptions.ServerConnectionException: SSL wrapped byte channel
 [Session: user=admin, cb={default} [ContentSource: user=admin, cb={none} [provider: SSLconn address=engrlab-130-159.engrlab.marklogic.com/172.18.130.159:9112, pool=0/64]]]
 [Client: XCC/9.0-1]
	at com.marklogic.mapreduce.ContentOutputFormat.checkOutputSpecs(ContentOutputFormat.java:233)
	at com.marklogic.mapreduce.MarkLogicOutputFormat.checkOutputSpecs(MarkLogicOutputFormat.java:92)
	... 12 more
Caused by: com.marklogic.xcc.exceptions.ServerConnectionException: SSL wrapped byte channel
 [Session: user=admin, cb={default} [ContentSource: user=admin, cb={none} [provider: SSLconn address=engrlab-130-159.engrlab.marklogic.com/172.18.130.159:9112, pool=0/64]]]
 [Client: XCC/9.0-1]
	at com.marklogic.xcc.impl.handlers.AbstractRequestController.runRequest(AbstractRequestController.java:149)
	at com.marklogic.xcc.impl.SessionImpl.submitRequestInternal(SessionImpl.java:437)
	at com.marklogic.xcc.impl.SessionImpl.submitRequest(SessionImpl.java:432)
	at com.marklogic.mapreduce.ContentOutputFormat.initialize(ContentOutputFormat.java:374)
	at com.marklogic.mapreduce.ContentOutputFormat.checkOutputSpecs(ContentOutputFormat.java:165)
	... 13 more
Caused by: java.io.EOFException: SSL wrapped byte channel
	at com.marklogic.io.SslByteChannel.handleHandshake(SslByteChannel.java:442)
	at com.marklogic.io.SslByteChannel.pushToEngine(SslByteChannel.java:401)
	at com.marklogic.io.SslByteChannel.write(SslByteChannel.java:361)
	at com.marklogic.http.HttpChannel.writeBuffer(HttpChannel.java:388)
	at com.marklogic.http.HttpChannel.writeHeaders(HttpChannel.java:380)
	at com.marklogic.http.HttpChannel.flushRequest(HttpChannel.java:361)
	at com.marklogic.http.HttpChannel.receiveMode(HttpChannel.java:286)
	at com.marklogic.http.HttpChannel.getResponseCode(HttpChannel.java:193)
	at com.marklogic.xcc.impl.handlers.EvalRequestController.serverDialog(EvalRequestController.java:76)
	at com.marklogic.xcc.impl.handlers.AbstractRequestController.runRequest(AbstractRequestController.java:88)
	... 17 more

ok

```

**Comment by jxchen-us** [comment]
Sravan will first make sure that both the source and destination app servers have SSL configured properly.
