### ISSUE TITLE
NullPointer Exception on ssl run

### ISSUE THREAD

**Issue by sravanr** [marklogic/marklogic-contentpump#49]
I am not able to reproduce this again but to make sure if we can find a reason on why this happen based on the data what we have

Here is the command I am using
```
 running following shell command: /space/Head/qa/mlcp/runmlcpHadoop.sh /space/Head/qa import -username admin -password admin -host engrlab-130-159.engrlab.marklogic.com -port 5275 -input_file_path file:///project/engineering/qa/mlcp/data/foo.bin -streaming true -document_type binary -output_uri_replace "foo,'foobug17062distributed'"
stderr/out from shell cmd: Today is SSL and Client_CERT enabled: true

IMPORT -conf /space/Head/qa/mlcp/mlcp-9.0/conf/MlcpSSLConfig.xml -username admin -password admin -host engrlab-130-159.engrlab.marklogic.com -port 5275 -input_file_path file:///project/engineering/qa/mlcp/data/foo.bin -streaming true -document_type binary -output_uri_replace foo,'foobug17062distributed'
###############SSL certificate location:- /project/qa/nightly-regression/ssl/user.p12

stderr/out from shell cmd: 16/11/08 00:43:29 INFO contentpump.LocalJobRunner: Content type: BINARY
16/11/08 00:43:29 INFO contentpump.ContentPump: Job name: distributed_791921316_1
16/11/08 00:43:29 INFO client.RMProxy: Connecting to ResourceManager at rh7v-intel64-cdh-1.marklogic.com/172.18.133.113:8032
16/11/08 00:43:31 INFO contentpump.FileAndDirectoryInputFormat: Total input paths to process : 1
16/11/08 00:43:31 INFO mapreduce.JobSubmitter: number of splits:1
16/11/08 00:43:31 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1475872281186_18660
16/11/08 00:43:31 INFO impl.YarnClientImpl: Submitted application application_1475872281186_18660
16/11/08 00:43:32 INFO mapreduce.Job: The url to track the job: http://rh7v-intel64-cdh-1.marklogic.com:8088/proxy/application_1475872281186_18660/
16/11/08 00:43:32 INFO mapreduce.Job: Running job: job_1475872281186_18660
16/11/08 00:43:37 INFO mapreduce.Job: Job job_1475872281186_18660 running in uber mode : false
16/11/08 00:43:37 INFO mapreduce.Job:  map 0% reduce 0%
16/11/08 00:43:42 INFO mapreduce.Job: Task Id : attempt_1475872281186_18660_m_000000_0, Status : FAILED
Error: java.lang.NullPointerException
        at com.marklogic.contentpump.StreamingDocumentReader.nextKeyValue(StreamingDocumentReader.java:42)
        at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:556)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:144)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1693)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

16/11/08 00:43:47 INFO mapreduce.Job:  map 100% reduce 0%
16/11/08 00:43:48 INFO mapreduce.Job: Job job_1475872281186_18660 completed successfully
16/11/08 00:43:48 INFO mapreduce.Job: Counters: 36
        File System Counters
                FILE: Number of bytes read=33554432
                FILE: Number of bytes written=140864
                FILE: Number of read operations=0
                FILE: Number of large read operations=0
                FILE: Number of write operations=0
                HDFS: Number of bytes read=122
                HDFS: Number of bytes written=0
                HDFS: Number of read operations=1
                HDFS: Number of large read operations=0
                 HDFS: Number of write operations=0
        Job Counters
                Failed map tasks=1
                Launched map tasks=2
                Other local map tasks=1
                Rack-local map tasks=1
                Total time spent by all maps in occupied slots (ms)=5778
                Total time spent by all reduces in occupied slots (ms)=0
                Total time spent by all map tasks (ms)=5778
                Total vcore-seconds taken by all map tasks=5778
                Total megabyte-seconds taken by all map tasks=5916672
        Map-Reduce Framework
                Map input records=1
                Map output records=1
                Input split bytes=122
                Spilled Records=0
                Failed Shuffles=0
                Merged Map outputs=0
                GC time elapsed (ms)=52
                CPU time spent (ms)=1920
                Physical memory (bytes) snapshot=258510848
                Virtual memory (bytes) snapshot=2791763968
                Total committed heap usage (bytes)=446693376
        com.marklogic.mapreduce.MarkLogicCounter
                INPUT_RECORDS=1
                OUTPUT_RECORDS=1
                OUTPUT_RECORDS_COMMITTED=1
                OUTPUT_RECORDS_FAILED=0
        File Input Format Counters
                Bytes Read=0
        File Output Format Counters
                Bytes Written=0
```

**Comment by jxchen-us** [comment]
I looked at the stack.  It's not related to SSL.  I don't see a bug and don't know how to reproduce.  So closing until we find a reliable test case.
