### ISSUE TITLE
Java heap space java.lang.OutOfMemoryError for large video files

### ISSUE THREAD

**Issue by masyukun** [marklogic/marklogic-contentpump#63]
Attempting to upload a 160MB MP4 video file resulted in a java.lang.OutOfMemoryError error. 

```
Last login: Fri Jun 23 16:42:08 2017 from 10.28.192.250
[xmartadm@ckpdb-app-stg-01 ~]$ cd /opt/data/marklogic_cisco/ingest/
[xmartadm@ckpdb-app-stg-01 ingest]$ ./ingest_data.sh BE6K_BenchDiskStatation_116_06232017.zip BE6K_BenchDiskStatation_116_06232017.csv BE6K_BenchDiskStatation_116
2017-06-23T16:48:03
Archive:  ../BE6K_BenchDiskStatation_116_06232017.zip
  inflating: bench_1_setup_synology.mp4
executing: /usr/local/mlcp/bin/mlcp.sh import -host localhost -port 8041 -username user -password password -input_file_path 'data/bench_1_setup_synology.mp4' -output_uri_replace ".*/ingest,''" -output_uri_prefix /kStatation_116  -transform_module /transform/ingest-dita.xqy -transform_namespace "http://marklogic.com/transform/ingest-dita" -transform_param "collType:dita-content^product:Cisco-BE-6000^release:11.6^role:Partner^solution:Cisco-Business-Edition^collections:BE6K_BenchDiskStatation_116^format:video^^function:Install" -output_collections "dita-content,BE6K_BenchDiskStatation_116" -output_permissions cisco-kms-role,read,cisco-kms-role,update

17/06/23 16:48:05 INFO contentpump.ContentPump: Hadoop library version: 2.0.0-alpha
17/06/23 16:48:05 INFO contentpump.LocalJobRunner: Content type is set to MIXED.  The format of the  inserted documents will be determined by the MIME  type specification configured on MarkLogic Server.
17/06/23 16:48:06 WARN util.KerberosName: Kerberos krb5 configuration not found, setting default realm to empty
17/06/23 16:48:06 INFO input.FileInputFormat: Total input paths to process : 1
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2017/06/23 16:48:07 - please wait.
JVMDUMP032I JVM requested System dump using '/opt/data/marklogic_cisco/ingest/core.20170623.164807.2200.0001.dmp' in response to an event
JVMDUMP012E Error in System dump: The core file created by child process with pid = 2227 was not found. Expected to find core file with name "/var/crash/core.pool-1-thread-1.2227"
JVMDUMP032I JVM requested Heap dump using '/opt/data/marklogic_cisco/ingest/heapdump.20170623.164807.2200.0002.phd' in response to an event
JVMDUMP010I Heap dump written to /opt/data/marklogic_cisco/ingest/heapdump.20170623.164807.2200.0002.phd
JVMDUMP032I JVM requested Java dump using '/opt/data/marklogic_cisco/ingest/javacore.20170623.164807.2200.0003.txt' in response to an event
JVMDUMP010I Java dump written to /opt/data/marklogic_cisco/ingest/javacore.20170623.164807.2200.0003.txt
JVMDUMP032I JVM requested Snap dump using '/opt/data/marklogic_cisco/ingest/Snap.20170623.164807.2200.0004.trc' in response to an event
17/06/23 16:48:13 INFO contentpump.LocalJobRunner:  completed 100%
JVMDUMP010I Snap dump written to /opt/data/marklogic_cisco/ingest/Snap.20170623.164807.2200.0004.trc
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
17/06/23 16:48:13 ERROR contentpump.MultithreadedMapper: Java heap space
java.lang.OutOfMemoryError: Java heap space
        at org.apache.hadoop.io.BytesWritable.setCapacity(BytesWritable.java:142)
        at org.apache.hadoop.io.BytesWritable.setSize(BytesWritable.java:121)
        at org.apache.hadoop.io.BytesWritable.readFields(BytesWritable.java:176)
        at org.apache.hadoop.io.serializer.WritableSerialization$WritableDeserializer.deserialize(WritableSerialization.java:73)
        at org.apache.hadoop.io.serializer.WritableSerialization$WritableDeserializer.deserialize(WritableSerialization.java:44)
        at org.apache.hadoop.util.ReflectionUtils.copy(ReflectionUtils.java:291)
        at com.marklogic.contentpump.MultithreadedMapper$SubMapRecordReader.nextKeyValue(MultithreadedMapper.java:287)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:76)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:85)
        at com.marklogic.contentpump.BaseMapper.runThreadSafe(BaseMapper.java:45)
        at com.marklogic.contentpump.MultithreadedMapper$MapRunner.run(MultithreadedMapper.java:376)
        at com.marklogic.contentpump.MultithreadedMapper.run(MultithreadedMapper.java:215)
        at com.marklogic.contentpump.LocalJobRunner$LocalMapTask.call(LocalJobRunner.java:376)
        at java.util.concurrent.FutureTask.run(FutureTask.java:277)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:785)
17/06/23 16:48:13 INFO contentpump.LocalJobRunner: com.marklogic.contentpump.ContentPumpStats:
17/06/23 16:48:13 INFO contentpump.LocalJobRunner: ATTEMPTED_INPUT_RECORD_COUNT: 0
17/06/23 16:48:13 INFO contentpump.LocalJobRunner: SKIPPED_INPUT_RECORD_COUNT: 0
17/06/23 16:48:13 INFO contentpump.LocalJobRunner: Total execution time: 6 sec
```

In the short term, we'll re-encode the videos to a lower resolution and frame rate. I've also made the longer-term recommendation to store the videos externally on a CDN. However, it would be good to have a fix; perhaps using streaming I/O methods so that the size of the file doesn't matter?

**Comment by mattsunsjf** [comment]
It looks like an old version of mlcp?

**Comment by mattsunsjf** [comment]
160 MB file doesn't sound big, what is the heap size you used? what's your machine capacity?
