### ISSUE TITLE
MLCP does not work against app servers with TLSv1.2

### ISSUE THREAD

**Issue by tternquist** [marklogic/marklogic-contentpump#77]
When using MLCP against an app server with TLSv1.2 configured (ciphers:ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD2:!MD5:!SSLv3), I am unable to load data.  This is with MarkLogic 9.0-5 and MLCP 9.0-5. Disabling TLS resolves issue.  See the below error:

```
2018-05-18T14:30:01.5551547Z 2018-05-18 10:30:01 WARN  MarkLogicOutputFormat:101 - Unable to connect to XXX-dev1.XYZ.com to query destination information
2018-05-18T14:30:01.5552080Z 2018-05-18 10:30:01 ERROR LocalJobRunner:159 - Error checking output specification: 
2018-05-18T14:30:01.5552371Z 2018-05-18 10:30:01 ERROR LocalJobRunner:160 - Unable to query destination information, no usable hostname found
2018-05-18T14:30:01.5554405Z :importAllEventDefinitions FAILED
2018-05-18T14:30:01.5671556Z :importAllEventDefinitions (Thread[Daemon worker,5,main]) completed. Took 8.56 secs.
2018-05-18T14:30:01.5690067Z ##[error]FAILURE: Build failed with an exception.
```

**Comment by jxchen-us** [comment]
Tom,

As of mlcp 9.0-5, you can specify the SSL protocol with -ssl_protocol option.  To connect to TLSv1.2, use "-ssl_protocol TLSv1.2".

**Comment by tternquist** [comment]
Thank you Jane. Will verify.

**Comment by tternquist** [comment]
Jane - We get an unrecognized option argument error:

```
2018-05-18T21:43:59.9073561Z mlcp arguments, excluding password: [IMPORT, -port, 8010, -transform_module, /com.marklogic.hub/mlcp-flow-transform.xqy, -document_type, json, -output_uri_replace, input/events/emp_events_definitions,'', -output_collections, LIFE_EVENT_DEFINITION,All-Event-Definitions,input, -input_file_path, input/events/emp_events_definitions, -transform_namespace, http://marklogic.com/data-hub/mlcp-flow-transform, -input_file_type, delimited_text, -output_permissions, rest-reader,read,rest-writer,update, -generate_uri, true, -transform_param, entity-name=LIFE_EVENT_DEFINITION,flow-name=All-Event-Definitions, -host, dev03.XXX.com, -username, admin, -ssl, -ssl_protocol TLSv1.2] 

```

```2018-05-18T21:44:04.4728909Z ##[error]java.lang.IllegalArgumentException: Unrecognized option argument for ssl: -ssl_protocol TLSv1.2
	at com.marklogic.contentpump.Command$1.applyConfigOptions(Command.java:648)
	at com.marklogic.contentpump.Command$1.createJob(Command.java:349)
	at com.marklogic.contentpump.ContentPump.runCommand(ContentPump.java:226)
	at com.marklogic.contentpump.ContentPump.main(ContentPump.java:74)
```
